### ISSUE TITLE
Raw pcm data in real time

### ISSUE THREAD

**Issue by cogmeta** [hungrymonkey/mic_stream#1]
How can I get raw pcm (16000, 16 bit) data in real time to be sent to server for speech recognition?

**Comment by hungrymonkey** [comment]
The whole point of the plugin is to send mic data onto the flutter platform. The pushes 16-bit audio clips onto flutter stream to allow it to be bind with other dart code.

If you want audio data to processed real-time onto a server, I think you should consider using Opus to compress the audio data before transmission.

I attempted to find opus plugins on the pub.dartlang but return zero matches.

https://pub.dartlang.org/packages?q=opus

here is a java implementation for opus. 

http://lists.xiph.org/pipermail/opus/2016-October/003653.html

https://github.com/lostromb/concentus

You either need to create an plugin to compress opus data or add an compression step to my plugin.

**Comment by hungrymonkey** [comment]
If you are ok with RAW pcm data, then you can just add a function that sends audio in clips directly with dart.

in every plugin project, there should be an example project. 

https://github.com/hungrymonkey/mic_stream/tree/master/example


here is mine, albeit the application is just really simple

most important code is here

https://github.com/hungrymonkey/mic_stream/blob/master/example/lib/main.dart#L19

You just need to add an listener to your project. With a listener callback, you can directly send audio to the server.

On other note, The whole point of the plugin is to send mic data onto the flutter platform. The pushes 16-bit audio clips onto flutter stream to allow it to be bind with other dart code.

If you want audio data to processed real-time onto a server, I think you should consider using Opus to compress the audio data before transmission. 
I attempted to find opus plugins on the pub.dartlang but return zero matches.

https://pub.dartlang.org/packages?q=opus

here is a java implementation for opus. 

http://lists.xiph.org/pipermail/opus/2016-October/003653.html

https://github.com/lostromb/concentus

You either need to create an plugin to compress opus data or add an compression step to my plugin.

**Comment by cogmeta** [comment]
@hungrymonkey Thank you so much. I will update you on the progress.

**Comment by hungrymonkey** [comment]
@cogmeta  no problem.  the only reason why I did not publish this project on dartlang, the project is inflexible.

There isn't switches to change bit rate, float, or period size. I have not added support for ios.

I dont have time to add all of these features
